#!/bin/bash

set -e
cd Tests/02_Evaluator
for s in *.5D
do
	er="${s%.5D}.expectedResult"
	gr="${s%.5D}.gotResult" 
	./testEvaluator "${s}" >"${gr}" || echo "failed: $s">&2
	diff -upr "${gr}" "${er}"
done
