
all:

clean:

distclean: clean

install:
	install -m 755 -d $(DESTDIR)/usr/share/6D/Assemblers
	install -m 644 X.5D $(DESTDIR)/usr/share/6D/Assemblers/X.5D
	install -m 644 X86.5D $(DESTDIR)/usr/share/6D/Assemblers/X86.5D
	install -m 644 AMD64.5D $(DESTDIR)/usr/share/6D/Assemblers/AMD64.5D
	install -m 644 ARM.5D $(DESTDIR)/usr/share/6D/Assemblers/ARM.5D
