#!/bin/bash

set -e
cd Tests/01_ShuntingYard
for s in *.5D
do
	echo "= $s"
	er="${s%.5D}.expectedResult"
	gr="${s%.5D}.gotResult" 
	./testShuntingYard "${s}" >"${gr}" || (echo "failed: $s">&2 ; false)
	diff -upr "${gr}" "${er}"
done
